[services]
lutris = True
gog = True
humblebundle = True
steam = True

[lutris]
library_ignores = 
migration_version = 10
dismiss-missing-vulkan-library-warning = True
width = 802
height = 600
window_x = 476
window_y = 379
maximized = False
selected_category = category:all

